version: 2

models:
  - name: stg_players
    description: This table contains basic information about players
    columns:
      - name: player_id
        tests:
          - unique
          - not_null
      - name: firstname
        tests:
          - not_null
      - name: lastname
        tests:
          - not_null
      - name: nationality
        tests:
          - not_null
          # - relationships:
          #     to: ref('players')
          #     field: id

  - name: stg_player_stats
    description: This table contains players statistics per season
    # description: '{{ doc("orders_status") }}'
    columns:
      - name: id
        tests:
          - unique
          - not_null
      # - name: status
      #   tests:
      #     - accepted_values:
      #         values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
