version: 2

models:
  - name: stg_players
    description: This table contains basic information about players
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: fullname
        tests:
          - not_null


  - name: stg_player_stats
    description: This table contains players statistics per season
    # description: '{{ doc("orders_status") }}'
    columns:
      - name: id
        tests:
          - unique
          - not_null
